stages:
  
  data_ingestion:
    cmd: python src/mnistClassifier/pipelines/stage_01_data_ingestion.py 
    deps:
      - src/mnistClassifier/pipelines/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data 
  
