stages:
  
  buidl_model:
    cmd: python src/mnistClassifier/pipelines/stage_00_build_model.py 
    deps:
      - src/mnistClassifier/pipelines/stage_00_build_model.py 
      - config/config.yaml
    params:
      - DENSE_SIZE
    outs:
      - artifacts/models/basemodel.h5:
          cache: false

  data_ingestion:
    cmd: python src/mnistClassifier/pipelines/stage_01_data_ingestion.py 
    deps:
      - src/mnistClassifier/pipelines/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data/train.csv:
          cache: false

  train_model:
    cmd: python src/mnistClassifier/pipelines/stage_02_train_model.py 
    deps:
      - src/mnistClassifier/pipelines/stage_02_train_model.py 
      - config/config.yaml
      - artifacts/models/basemodel.h5
      - artifacts/data/train.csv
      - artifacts/data/test.csv
    params:
      - EPOCHS
      - BATCH_SIZE

  evaluate_model:
    cmd: python src/mnistClassifier/pipelines/stage_03_evaluate_model.py 
    deps:
      - src/mnistClassifier/pipelines/stage_03_evaluate_model.py 
      - config/config.yaml
      - artifacts/models/model.h5
      - artifacts/models/preprocessor.pkl
      