data_ingestion:
  data_url: https://drive.usercontent.google.com/u/0/uc?id=1CIoKzOYAUrU0z7lxTXNtOuRC89V1ISui&export=download
  raw_data_path: artifacts/data/data.csv 
  train_data_path: artifacts/data/train.csv
  test_data_path: artifacts/data/test.csv 
  extract_data_path: artifacts/data/
  download_path: artifacts/data/data.zip


data_preprocessing:
  data_preprocessor_path: artifacts/models/preprocessor.pkl 
  train_path: artifacts/data/train.csv
  test_path: artifacts/data/test.csv
train_model:
  trained_model_path: artifacts/models/model.h5


evaluate_model:
  trained_model_path: artifacts/models/model.h5
